# Site settings
name: Jason.Tao
email: taozhuwen@126.com
author: Jason.Tao
url: https://blog.csdn.net/taozhuwen
resume_site: https://blog.csdn.net/taozhuwen
github: https://github.com/taozhuwen/
baseurl: ''
description: 活到老，学到老！！！
meta_description: 学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: 那些没能将你打败的东西，都会让你变得更加强大；
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: taozhuwen

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

